server:
  port: 8083
  http:
    port: 8003
  servlet:
    context-path: /submission
  ssl:
    enabled: true
    key-alias: submission-https
    key-store: classpath:ssl/submission.jks
    key-store-type: JKS
    key-store-password: dinhanst2832004
    key-password: dinhanst2832004

spring:
  application:
    name: submission-service
